image: stgit.dcs.gla.ac.uk:5050/team-project-h/2025/sh22/sh22-main/django-test:20251126

variables:
  DJANGO_SECRET_KEY: ci-test-only-secret-key

stages:
  - lint
  - test

lint_django:
  stage: lint
  script:
    - pip install -r requirements.txt
    - pylint fergusonbequest --fail-under=8.0 --exit-zero

test_django:
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test fergusonbequest.tests --verbosity=2

