# Generated by Django 5.2.8 on 2026-03-16 01:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("description", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("terms", models.TextField(blank=True)),
                ("booking_open", models.DateTimeField(blank=True, null=True)),
                ("booking_close", models.DateTimeField(blank=True, null=True)),
                ("per_year_limit", models.PositiveIntegerField(default=3)),
                (
                    "attraction_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Attraction"),
                            ("weekly_event", "Weekly Ticket Event"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TicketDraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("description", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("terms", models.TextField(blank=True)),
                ("booking_open", models.DateTimeField(blank=True, null=True)),
                ("booking_close", models.DateTimeField(blank=True, null=True)),
                ("draw_date", models.DateTimeField()),
                ("per_year_limit", models.PositiveIntegerField(default=3)),
                (
                    "attraction_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Attraction"),
                            ("weekly_event", "Weekly Ticket Event"),
                        ],
                        default="weekly_event",
                        max_length=20,
                    ),
                ),
                ("winner_selected_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttractionSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("why_recommended", models.TextField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("implemented", "Implemented"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attraction_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                (
                    "num_tickets",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                ("agreed_terms", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "ticket_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cancel_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Users can cancel their booking until this date/time. Leave empty for 'no cancellation allowed'.",
                        null=True,
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("codes", "E-ticket codes"),
                            ("pdf_template", "PDF template"),
                            ("pdf_template_random", "PDF template + random code"),
                            ("pdf_individual", "Individual PDF tickets"),
                            ("qr_individual", "Individual QR tickets"),
                            ("booking_code", "Generic booking code"),
                            ("instructions", "Staff-card instructions"),
                            ("box_office", "Box office collection"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("ticket_sent", models.BooleanField(default=False)),
                ("ticket_sent_at", models.DateTimeField(blank=True, null=True)),
                ("ticket_instructions", models.TextField(blank=True, null=True)),
                (
                    "generic_booking_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ticket_qr_value", models.TextField(blank=True, null=True)),
                ("ticket_visible_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ticket_release_days",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="How many days before the visit date the ticket becomes visible to the user.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fergusonbequest.attraction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BookingTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="tickets/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="fergusonbequest.booking",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("attraction_confirmation", "Attraction Confirmation"),
                            ("draw_confirmation", "Ticket Draw Confirmation"),
                            ("attraction_cancellation", "Attraction Cancellation"),
                            ("draw_cancellation", "Ticket Draw Cancellation"),
                            (
                                "attraction_distribution",
                                "Attraction Ticket Distribution",
                            ),
                            ("draw_distribution", "Ticket Draw Ticket Distribution"),
                            ("draw_winner", "Ticket Draw Winner"),
                            (
                                "attraction_reallocation",
                                "Attraction Reallocation (Next in waiting list)",
                            ),
                            (
                                "draw_reallocation",
                                "Ticket Draw Reallocation (Redraw Winner)",
                            ),
                            ("attraction_reminder", "Attraction Reminder"),
                            ("draw_reminder", "Ticket Draw Reminder"),
                            ("announcement", "Announcements"),
                            ("custom", "Custom"),
                        ],
                        default="confirmation",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=250)),
                ("body", models.TextField()),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this as the default template for this email type",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("type",),
                        name="unique_default_per_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_guid",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("eligible", models.BooleanField(default=False)),
                ("eligibility_reason", models.TextField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketDrawBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("num_tickets", models.PositiveIntegerField(default=1)),
                ("agreed_terms", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled", models.BooleanField(default=False)),
                ("is_accepted", models.BooleanField(default=False)),
                (
                    "converted_booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_draw_booking",
                        to="fergusonbequest.booking",
                    ),
                ),
                (
                    "ticket_draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fergusonbequest.ticketdraw",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_draw_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="ticketdraw",
            name="winner_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_for_draw",
                to="fergusonbequest.ticketdrawbooking",
            ),
        ),
        migrations.CreateModel(
            name="TicketDrawVisitSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(default=20)),
                ("remaining", models.PositiveIntegerField(default=20)),
                (
                    "ticket_draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="fergusonbequest.ticketdraw",
                    ),
                ),
            ],
            options={
                "ordering": ("date", "time"),
            },
        ),
        migrations.AddField(
            model_name="ticketdrawbooking",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="fergusonbequest.ticketdrawvisitslot",
            ),
        ),
        migrations.CreateModel(
            name="VisitSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(default=20)),
                ("remaining", models.PositiveIntegerField(default=20)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="fergusonbequest.attraction",
                    ),
                ),
            ],
            options={
                "ordering": ("date", "time"),
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="fergusonbequest.visitslot",
            ),
        ),
        migrations.CreateModel(
            name="AttractionWaitlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled", models.BooleanField(default=False)),
                ("notified", models.BooleanField(default=False)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="fergusonbequest.attraction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attraction_waitlist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="fergusonbequest.visitslot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cancelled", False)),
                fields=("user", "slot"),
                name="unique_active_booking_per_slot_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="attractionwaitlistentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cancelled", False)),
                fields=("user", "slot"),
                name="unique_active_slot_waitlist",
            ),
        ),
    ]
