# Generated by Django 5.2.8 on 2026-03-14 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attractionwaitlistentry",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to="fergusonbequest.visitslot",
            ),
        ),
    ]
