# Generated by Django 5.2.8 on 2026-03-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='cancel_deadline',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_deadline',
            field=models.DateTimeField(blank=True, help_text="Users can cancel their booking until this date/time. Leave empty for 'no cancellation allowed'.", null=True),
        ),
    ]
