# Generated by Django 5.2.8 on 2026-03-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="box_office_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
