# Generated by Django 5.2.8 on 2026-03-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0002_booking_box_office_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingticket",
            name="qr_value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
