# Generated by Django 5.2.8 on 2026-03-14 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0002_attractionwaitlistentry_slot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attractionwaitlistentry",
            name="unique_active_attraction_waitlist",
        ),
        migrations.AddConstraint(
            model_name="attractionwaitlistentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cancelled", False)),
                fields=("user", "slot"),
                name="unique_active_slot_waitlist",
            ),
        ),
    ]
