# Generated by Django 5.2.8 on 2026-03-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0003_bookingticket_qr_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingticket",
            name="ticket_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
