# Generated by Django 5.2.8 on 2026-03-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0002_remove_attraction_cancel_deadline_and_more'),
        ('fergusonbequest', '0003_remove_attractionwaitlistentry_unique_active_attraction_waitlist_and_more'),
    ]

    operations = [
    ]
