# Generated by Django 5.2.8 on 2026-01-19 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0004_booking_ticket_code_alter_attraction_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('terms', models.TextField(blank=True)),
                ('booking_open', models.DateTimeField(blank=True, null=True)),
                ('booking_close', models.DateTimeField(blank=True, null=True)),
                ('draw_date', models.DateTimeField()),
                ('per_year_limit', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDrawBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('agreed_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('ticket_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fergusonbequest.ticketdraw')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fergusonbequest.visitslot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_draw_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
