# Generated by Django 5.2.8 on 2026-01-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0005_ticketdraw_ticketdrawbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketdrawbooking',
            old_name='attraction',
            new_name='ticket_draw',
        ),
    ]
