# Generated by Django 5.2.8 on 2026-01-19 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0006_rename_attraction_ticketdrawbooking_ticket_draw'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDrawVisitSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('remaining', models.PositiveIntegerField(default=20)),
                ('ticket_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='fergusonbequest.ticketdraw')),
            ],
            options={
                'ordering': ('date', 'time'),
            },
        ),
    ]
