# Generated by Django 5.2.8 on 2026-01-21 01:15
# pylint: skip-file
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0007_ticketdrawvisitslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketdrawbooking",
            name="num_tickets",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ticketdrawbooking",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="fergusonbequest.ticketdrawvisitslot",
            ),
        ),
    ]
