# Generated by Django 5.2.8 on 2026-01-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0008_ticketdrawbooking_num_tickets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
