# Generated by Django 5.2.8 on 2026-02-04 09:58

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0008_ticketdrawbooking_num_tickets_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="num_tickets",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cancelled", False)),
                fields=("user", "attraction"),
                name="unique_active_booking_per_attraction_per_user",
            ),
        ),
    ]
