# Generated by Django 5.2.8 on 2026-02-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0009_attraction_duration_minutes"),
        ("fergusonbequest", "0009_booking_num_tickets_and_more"),
    ]

    operations = []
