# Generated by Django 5.2.8 on 2026-02-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0009_attraction_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='attraction_type',
            field=models.CharField(choices=[('regular', 'Regular Attraction'), ('weekly_event', 'Weekly Ticket Event')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketdraw',
            name='attraction_type',
            field=models.CharField(choices=[('regular', 'Regular Attraction'), ('weekly_event', 'Weekly Ticket Event')], default='weekly_event', max_length=20),
        ),
    ]
