# Generated by Django 5.2.8 on 2026-02-04 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0010_merge_20260204_1458"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_active_booking_per_attraction_per_user",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cancelled", False)),
                fields=("user", "slot"),
                name="unique_active_booking_per_slot_per_user",
            ),
        ),
    ]
