# Generated by Django 5.2.8 on 2026-02-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fergusonbequest",
            "0011_remove_booking_unique_active_booking_per_attraction_per_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="cancel_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Users can cancel their booking until this date/time. Leave empty for 'no cancellation allowed'.",
                null=True,
            ),
        ),
    ]
