# Generated by Django 5.2.8 on 2026-02-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0011_remove_booking_unique_active_booking_per_attraction_per_user_and_more"),
        ("fergusonbequest", "0012_attraction_cancel_deadline"),
    ]

    operations = []
