# Generated by Django 2.2.28 on 2026-02-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0010_auto_20260209_1756'),
        ('fergusonbequest', '0012_attraction_cancel_deadline'),
    ]

    operations = [
    ]
