# Generated by Django 5.2.8 on 2026-02-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0013_merge_20260209_1855"),
        ("fergusonbequest", "0013_merge_20260211_1419"),
    ]

    operations = []
