# Generated by Django 5.2.8 on 2026-02-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0010_attraction_attraction_type_and_more'),
        ('fergusonbequest', '0014_merge_20260213_1230'),
    ]

    operations = [
    ]
