# Generated by Django 5.2.8 on 2026-02-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0012_attraction_cancel_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='How was your visit to {attraction_name}?', help_text='Email subject. Use {attraction_name} as placeholder for the attraction name.', max_length=200)),
                ('body', models.TextField(default="Dear {user_name},\n\nThank you for using the Ferguson Bequest to visit {attraction_name} on {visit_date}.\n\nWe hope you enjoyed your experience! We'd love to hear your feedback to help us improve the Ferguson Bequest service.\n\nPlease take a few moments to complete our feedback form:\n{feedback_url}\n\nYour feedback is valuable and helps us provide better experiences for all University of Glasgow staff and students.\n\nBest regards,\nThe Ferguson Bequest Team\n\n---\nThis is an automated email. For queries, contact fergusonbequest@glasgow.ac.uk", help_text='Email body. Available placeholders: {user_name}, {attraction_name}, {visit_date}, {feedback_url}')),
                ('enabled', models.BooleanField(default=True, help_text='Uncheck to disable automatic feedback emails')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback Email Template',
                'verbose_name_plural': 'Feedback Email Template',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='feedback_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
