# Generated by Django 5.2.8 on 2026-02-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0015_ticketdraw_winner_booking_and_more"),
        (
            "fergusonbequest",
            "0015_ticketdrawbooking_is_accepted_alter_attraction_id_and_more",
        ),
    ]

    operations = []
