# Generated by Django 5.2.8 on 2026-02-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0016_feedbackemailtemplate_booking_feedback_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackemailtemplate',
            name='feedback_url',
            field=models.URLField(default='https://forms.office.com/Pages/ResponsePage.aspx?id=KVxybjp2UE-B8i4lTwEzyKi8RE5OIhlLqu3FN1D5vsBUREFDRUZKQUxCWEdMTlBXT1VRN0NHTTNYSy4u', help_text='Microsoft Forms feedback URL. Create your form and paste the link here.', max_length=500),
        ),
    ]
