# Generated by Django 5.2.8 on 2026-02-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0015_merge_20260216_1600"),
        ("fergusonbequest", "0016_merge_20260218_1221"),
    ]

    operations = []
