# Generated by Django 5.2.8 on 2026-02-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0017_feedbackemailtemplate_feedback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackemailtemplate',
            name='body',
            field=models.TextField(default="Dear {user_name},\n\nThank you for using the Ferguson Bequest to visit {attraction_name} on {visit_date}.\n\nWe hope you enjoyed your experience! We'd love to hear your feedback to help us improve the Ferguson Bequest service.\n\nPlease take a few moments to complete our feedback form:\n{feedback_url}\n\nYour feedback is valuable and helps us provide better experiences for all University of Glasgow staff.\n\nBest regards,\nThe Ferguson Bequest Team\n\n---\nThis is an automated email. For queries, contact fergusonbequest@glasgow.ac.uk", help_text='Email body. Available placeholders: {user_name}, {attraction_name}, {visit_date}, {feedback_url}'),
        ),
        migrations.AlterField(
            model_name='feedbackemailtemplate',
            name='feedback_url',
            field=models.URLField(blank=True, default='', help_text='Microsoft Forms feedback URL. Create your form in Microsoft Forms and paste the link here. This field is required to send feedback emails.', max_length=500),
        ),
    ]
