# Generated by Django 5.2.8 on 2026-02-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0017_merge_20260218_1234"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ticket_file",
            field=models.FileField(blank=True, null=True, upload_to="tickets/"),
        ),
        migrations.AddField(
            model_name="booking",
            name="ticket_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="ticket_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="ticket_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="ticket_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
