# Generated by Django 5.2.8 on 2026-02-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0015_merge_20260216_1600'),
        ('fergusonbequest', '0018_alter_feedbackemailtemplate_body_and_more'),
    ]

    operations = [
    ]
