# Generated by Django 5.2.8 on 2026-02-25 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0018_booking_ticket_file_booking_ticket_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ticket_release_days",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many days before the visit date the ticket becomes visible to the user.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
    ]
