# Generated by Django 5.2.8 on 2026-03-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0019_booking_ticket_release_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="generic_booking_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="ticket_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="ticket_qr_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="ticket_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("codes", "E-ticket codes"),
                    ("pdf_template", "PDF template"),
                    ("pdf_template_random", "PDF template + random code"),
                    ("pdf_individual", "Individual PDF tickets"),
                    ("qr_individual", "Individual QR tickets"),
                    ("booking_code", "Generic booking code"),
                    ("instructions", "Staff-card instructions"),
                    ("box_office", "Box office collection"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
