# Generated by Django 5.2.8 on 2026-03-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0019_alter_attraction_id_alter_attractionsuggestion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('attraction_confirmation', 'Attraction Confirmation'), ('draw_confirmation', 'Ticket Draw Confirmation'), ('attraction_cancellation', 'Attraction Cancellation'), ('draw_cancellation', 'Ticket Draw Cancellation'), ('attraction_distribution', 'Attraction Ticket Distribution'), ('draw_distribution', 'Ticket Draw Ticket Distribution'), ('draw_winner', 'Ticket Draw Winner'), ('attraction_reallocation', 'Attraction Reallocation (Next in waiting list)'), ('draw_reallocation', 'Ticket Draw Reallocation (Redraw Winner)'), ('attraction_reminder', 'Attraction Reminder'), ('draw_reminder', 'Ticket Draw Reminder'), ('feedback', 'Feedback'), ('accouncement', 'Announcements'), ('custom', 'Custom')], default='confirmation', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default template for this email type')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('type',), name='unique_default_per_type')],
            },
        ),
    ]
