# Generated by Django 5.2.8 on 2026-03-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0020_booking_generic_booking_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ticket_visible_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
