# Generated by Django 5.2.8 on 2026-02-24

from django.db import migrations


def create_feedback_template_table(apps, schema_editor):
    FeedbackEmailTemplate = apps.get_model('fergusonbequest', 'FeedbackEmailTemplate')
    table_name = FeedbackEmailTemplate._meta.db_table
    existing_tables = schema_editor.connection.introspection.table_names()
    if table_name not in existing_tables:
        schema_editor.create_model(FeedbackEmailTemplate)


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0020_alter_attraction_id_alter_attractionsuggestion_id_and_more'),
    ]

    operations = [
        migrations.RunPython(create_feedback_template_table, migrations.RunPython.noop),
    ]
