# Generated by Django 5.2.8 on 2026-03-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0021_booking_ticket_sent_alter_emailtemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdrawbooking',
            name='tickticket_sent',
            field=models.BooleanField(default=False),
        ),
    ]
