# Generated by Django 5.2.8 on 2026-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0021_booking_ticket_visible_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketdrawbooking",
            name="generic_booking_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ticketdrawbooking",
            name="ticket_file",
            field=models.FileField(blank=True, null=True, upload_to="tickets/"),
        ),
        migrations.AddField(
            model_name="ticketdrawbooking",
            name="ticket_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketdrawbooking",
            name="ticket_qr_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketdrawbooking",
            name="ticket_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticketdrawbooking",
            name="ticket_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketdrawbooking",
            name="ticket_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("codes", "E-ticket codes"),
                    ("pdf_template", "PDF template"),
                    ("pdf_template_random", "PDF template + random code"),
                    ("pdf_individual", "Individual PDF tickets"),
                    ("qr_individual", "Individual QR tickets"),
                    ("booking_code", "Generic booking code"),
                    ("instructions", "Staff-card instructions"),
                    ("box_office", "Box office collection"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticketdrawbooking",
            name="ticket_visible_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticketdrawbooking",
            name="ticket_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
