# Generated by Django 5.2.8 on 2026-03-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0022_ticketdrawbooking_tickticket_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketdrawbooking',
            old_name='tickticket_sent',
            new_name='ticket_sent',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('attraction_confirmation', 'Attraction Confirmation'), ('draw_confirmation', 'Ticket Draw Confirmation'), ('attraction_cancellation', 'Attraction Cancellation'), ('draw_cancellation', 'Ticket Draw Cancellation'), ('attraction_distribution', 'Attraction Ticket Distribution'), ('draw_distribution', 'Ticket Draw Ticket Distribution'), ('draw_winner', 'Ticket Draw Winner'), ('attraction_reallocation', 'Attraction Reallocation (Next in waiting list)'), ('draw_reallocation', 'Ticket Draw Reallocation (Redraw Winner)'), ('attraction_reminder', 'Attraction Reminder'), ('draw_reminder', 'Ticket Draw Reminder'), ('announcement', 'Announcements'), ('custom', 'Custom')], default='confirmation', max_length=100),
        ),
    ]
