# Generated by Django 5.2.8 on 2026-03-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0021_repair_attraction_waitlist_schema'),
        ('fergusonbequest', '0023_rename_tickticket_sent_ticketdrawbooking_ticket_sent_and_more'),
    ]

    operations = [
    ]
