# Generated by Django 5.2.8 on 2026-03-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0021_create_feedbackemailtemplate_table'),
    ]

    operations = [
    ]
