# Generated by Django 5.2.8 on 2026-03-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0005_termsandconditions'),
        ('fergusonbequest', '0027_repair_booking_feedback_email_sent_column'),
    ]

    operations = [
    ]
