# Generated by Django 5.2.8 on 2026-03-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0028_merge_20260318_0932'),
        ('fergusonbequest', '0028_seed_feedback_email_defaults'),
    ]

    operations = [
    ]
