# Generated by Django 5.2.8 on 2026-03-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0005_repair_attractionwaitlistentry_slot_column"),
        ("fergusonbequest", "0029_merge_20260318_1348"),
    ]

    operations = []
