# Generated by Django 5.2.8 on 2026-03-23 11:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0030_merge_20260323_1125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='feedback_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='feedback_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackemailtemplate',
            name='expiry_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Number of days after the visit when feedback submissions remain open.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='feedbackemailtemplate',
            name='feedback_mode',
            field=models.CharField(choices=[('internal', 'Built-in feedback form'), ('external', 'External Microsoft Forms link')], default='internal', help_text='Choose whether emails link to the in-app feedback form or an external Microsoft Forms URL.', max_length=20),
        ),
        migrations.AddField(
            model_name='feedbackemailtemplate',
            name='reminder_delay_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Days after the first feedback email to send the reminder.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='feedbackemailtemplate',
            name='reminder_enabled',
            field=models.BooleanField(default=True, help_text='Send one reminder email when no feedback is submitted.'),
        ),
        migrations.CreateModel(
            name='BookingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True)),
                ('staff_full_name', models.CharField(max_length=150)),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_guid', models.CharField(blank=True, max_length=64)),
                ('staff_department', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submission', to='fergusonbequest.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
    ]
