# Generated by Django 5.2.8 on 2026-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0030_merge_20260322_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_intro', models.TextField(default='The Ferguson Bequest gives University of Glasgow staff exclusive access to attractions and event ticket draws throughout the year.')),
                ('left_bullet_1', models.CharField(default='Apply for up to three attractions per calendar year', max_length=255)),
                ('left_bullet_2', models.CharField(default='Enter multiple ticket draws and win once per year', max_length=255)),
                ('left_bullet_3', models.CharField(default='View all your bookings in Booking History', max_length=255)),
                ('left_warning_title', models.CharField(default='Please apply carefully', max_length=200)),
                ('left_warning_body', models.TextField(default='bookings can’t be cancelled once submitted.')),
                ('left_eligibility_text', models.TextField(default='Eligible for University of Glasgow staff with an active contract of employment. Honorary, affiliate, and casual staff are not eligible.')),
                ('about_heading', models.CharField(default='About the Ferguson Bequest', max_length=200)),
                ('about_paragraph_1', models.TextField(default='Professor in Public Health and President of the University Athletics Football Club, Professor Thomas Ferguson authored classic studies on the origin of Scotland’s social and health services. In 1977 he bequeathed his estate to the University, with the instruction that the money be used to foster the social side of University life for its (then) 2,100 staff.')),
                ('about_paragraph_2', models.TextField(default='The University Court established a committee (the Ferguson Bequest Committee) to administer the funds. Various corporate memberships and theatre ticket draws are administered by the Court Office on behalf of the Ferguson Bequest Committee.')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
