# Generated by Django 5.2.8 on 2026-03-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0031_mainpagecontent'),
    ]

    operations = [
    ]
