# Generated by Django 5.2.8 on 2026-03-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fergusonbequest', '0032_initialize_main_page_content'),
        ('fergusonbequest', '0034_merge_feedback_branch_heads'),
    ]

    operations = [
    ]
