# Generated by Django 5.2.8 on 2026-03-23 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0034_merge_feedback_branch_heads"),
    ]

    operations = [
        migrations.AddField(
            model_name="attractionwaitlistentry",
            name="num_tickets",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
    ]
