# Generated by Django 5.2.8 on 2026-03-24 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0035_attractionwaitlistentry_num_tickets"),
        ("fergusonbequest", "0035_merge_20260323_2228"),
    ]

    operations = []
