# Generated by Django 5.2.8 on 2026-03-24 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0036_merge_20260324_0215"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attractionwaitlistentry",
            name="num_tickets",
        ),
    ]
