# Generated by Django 5.2.8 on 2026-03-24 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fergusonbequest", "0037_remove_attractionwaitlistentry_num_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="attractionwaitlistentry",
            name="num_tickets",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
    ]
